### ISSUE TITLE
Case-insensitive matching?

### ISSUE THREAD

**Issue by DavidAccola** [nwutils/find-in-nw#21]
By default, seems like matching is case sensitive. Can this be changed?

Request:
Looking for case-insensitive matching a la Chrome's Ctrl+F search or the findAndReplaceDOMText [demo](https://padolsey.github.io/findAndReplaceDOMText/demo.html).

Example:
Text to search: "Test Results: 5 tests"
Search term: "test"
Current results: "Test Results: 5 **test**s"
Desired results: "**Test** Results: 5 **test**s"

If this is easily configurable and I'm just missing it, please fill me in! Thanks!

**Comment by TheJaredWilcurt** [comment]
Fixed in v1.2.0.

You can also now pass in any `findAndReplaceDOMText` options.
