### ISSUE TITLE
Space is being added at beginning and end of highlighting

### ISSUE THREAD

**Issue by DavidAccola** [nwutils/find-in-nw#22]
I'm am noticing some weirdness around highlighting causing text to jump, like a space is being added at the beginning and end of the highlighting.

Example:
![text jump](https://user-images.githubusercontent.com/62493194/221332812-b1f6ac71-13eb-43a5-9654-d0bb593721ec.gif)

I'm attaching an example html file. 

Context: Working on adding find-in-nw to html reports generated with with [htmlextra](https://github.com/DannyDainton/newman-reporter-htmlextra)

[Example.zip](https://github.com/nwutils/find-in-nw/files/10830119/Example.zip)

**Comment by TheJaredWilcurt** [comment]
You are using bootstrap which has this code:
```css
mark {
  padding: 0.2em;
}
```
Add this code

```html
<style>
mark {
  padding: 0px !important;
}
</style>
```

**Comment by DavidAccola** [comment]
Makes sense! Thanks!
