### ISSUE TITLE
Identifier 'findInNw' has already been declared

### ISSUE THREAD

**Issue by DavidAccola** [nwutils/find-in-nw#24]
What is a good way to use find-in-nw within an iFrame whose contents change while my app is running?

**Context:** My nw.js app makes a program (newman) generate a report.html file when I click a button. I then display that report.html in an iframe in my app. So that I can Ctrl+F its contents within my app, I inject the following into its body:

```
<script src="_scripts/find-in-nw.js"></script>
<script>findInNw.initialize({ classesToIgnore: ['arrow', 'backToTop', 'nav-item', 'tooltip'], idsToIgnore: ['openAll', 'openAllFailed', 'openAllRequests', 'showOnlyFailures'] });</script>
```

I do that like this:
```
const iframe = document.getElementById("frame-iframe");
					// Wait for the iframe to load
					iframe.addEventListener("load", function () {

						// Insert style into the iframe
						const style = iframe.contentWindow.document.createElement("style");
						style.innerHTML = `
		                            #find-in-nw-search-box {top:34px;}
		                            #find-in-nw-case-sensitive {display: none;}
		                            mark {padding: 0px !important;}
		                            mark.find-in-nw-token {background-color: #FFF36D;}
									mark.find-in-nw-current-token {background-color: #FAC761; color: black;}
		                        `;
						iframe.contentWindow.document.head.appendChild(style);

						// Insert script reference into iframe
						const script1 = iframe.contentWindow.document.createElement("script");
						script1.src = "_scripts/find-in-nw.js";
						iframe.contentWindow.document.head.appendChild(script1);

						// Wait for the first script to load
						script1.addEventListener("load", function () {

							// Insert the script initialize into the iframe
							const script2 = iframe.contentWindow.document.createElement("script");
							script2.text = "findInNw.initialize({classesToIgnore: ['arrow','backToTop','nav-item','tooltip'],idsToIgnore: ['openAll','openAllFailed','openAllRequests','showOnlyFailures']});";
							iframe.contentWindow.document.head.appendChild(script2);
						});

					});
```

**Issue:** Every time I click the button, the html file is re-generated fresh by the CLI, so each time I have to re-inject the script tags. This results in the following error:
```
Uncaught SyntaxError: Identifier 'findInNw' has already been declared (at find-in-nw.js:1:1)
```

I either need to catch that error and handle it gracefully (which I haven't been able to find a way to do), or need some advice on a good method for using find-in-nw in an iFrame whose contents change.

**Comment by TheJaredWilcurt** [comment]
This library wasn't designed to work with IFrames. It scans the DOM for matching text. Some ideas:

* Destroy the iframe with JavaScript from the DOM, and create a new `<iframe>` element to be inserted into the DOM and re-apply the injection
* Read in the contents of the HTML file as a string, remove everything before and after `<body>`/`</body>` so you just have the markup and then `innerHTML` that into you page
  * This wouldn't handle unique styling or scripts well though. Also `innerHTML` can cause XSS if the content is untrusted
* Modify the file contents saved to the disk so that the HTML files have the find-in-nw import stored in them
* You could test if the `findInNw` function already exists, and if not, it will inject the script to run it

```html
<script>window.findInNw || document.write('<script src="_scripts/find-in-nw.js"><\/script>')</script>
<script>
findInNw.initialize({
  classesToIgnore: [
    'arrow',
    'backToTop',
    'nav-item',
    'tooltip'
  ],
  idsToIgnore: [
    'openAll',
    'openAllFailed',
    'openAllRequests',
    'showOnlyFailures'
  ]
});
</script>
```

**Comment by DavidAccola** [comment]
Thanks for the ideas! I've gone the route of modifying the files saved to disk.

One snag I ran into there is that if the user then opens the html file directly in a browser, the browser uses find-in-nw instead of its built in Ctrl+F. Detecting nw.js by checking for nw.gui and only initializing if that can be found worked for my use case:
```
<script>
function is_nwjs(){
    try{
        return (typeof require('nw.gui') !== "undefined");
    } catch (e){
        return false;
    }
}

if (is_nwjs()){
findInNw.initialize({
  classesToIgnore: [
    'arrow',
    'backToTop',
    'nav-item',
    'tooltip'
  ],
  idsToIgnore: [
    'openAll',
    'openAllFailed',
    'openAllRequests',
    'showOnlyFailures'
  ]
});
}
</script>
```

Feel free to close this out!

**Comment by TheJaredWilcurt** [comment]
Rather than doing a try/catch (which throws not because `nw` isn't present, but because `require` is undefined), you can just check if `window.nw` is defined.
```js
if (window.nw) {
  findInNw.initialize({
    classesToIgnore: [
      'arrow',
      'backToTop',
      'nav-item',
      'tooltip'
    ],
    idsToIgnore: [
      'openAll',
      'openAllFailed',
      'openAllRequests',
      'showOnlyFailures'
    ]
  });
}
```

**Comment by DavidAccola** [comment]
Thanks for the tip! I'll do that.
